# Generated by Django 5.2.4 on 2025-07-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="description",
        ),
    ]
